/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webwallet_free: (a: number, b: number) => void;
export const blake3_hash_hex: (a: number, b: number, c: number) => void;
export const compute_coin_id_hex: (a: number, b: number, c: number, d: bigint, e: number, f: number) => void;
export const decrypt_cli_wallet: (a: number, b: number, c: number, d: number, e: number) => void;
export const generate_phrase: (a: number) => void;
export const mine_commitment_pow: (a: number, b: number, c: number) => bigint;
export const search_nonces: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number) => void;
export const webwallet_build_coinbase: (a: number, b: number, c: bigint, d: number) => void;
export const webwallet_build_reveal: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const webwallet_build_solo_extension: (a: number, b: number, c: number, d: number, e: bigint) => void;
export const webwallet_build_state_thread_tx: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number) => void;
export const webwallet_check_filter: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const webwallet_export_mss_bytes: (a: number, b: number, c: number, d: number) => void;
export const webwallet_from_seed_hex: (a: number, b: number, c: number) => void;
export const webwallet_get_mss_address: (a: number, b: number, c: number, d: number, e: number) => void;
export const webwallet_get_wots_address: (a: number, b: number, c: number) => void;
export const webwallet_has_mss_cache: (a: number, b: number, c: number) => number;
export const webwallet_import_mss_bytes: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const webwallet_new: (a: number, b: number, c: number) => void;
export const webwallet_prepare_spend: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint, h: number) => void;
export const webwallet_set_mss_leaf_index: (a: number, b: number, c: number, d: number) => void;
export const webwallet_set_watchlist: (a: number, b: number, c: number) => void;
export const decompose_amount: (a: bigint) => number;
export const __wbindgen_export: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
